---
hugging_face:
  model_id: deepseek-ai/DeepSeek-R1-Distill-Qwen-32B
lite_llm:
  model_id: ollama_chat/mistral
  api_base: http://localhost:11434
open_ai:
  model_id: gpt-4o-mini
  api_base: https://api.openai.com/v1/
max_workers: 10